//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineWarehousingInformationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int productID { get; set; }
        public int totalQuantity { get; set; }
        public System.DateTime updateDate { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
