//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineWarehousingInformationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Packages()
        {
            this.PackageContents = new HashSet<PackageContents>();
        }
    
        public int packageID { get; set; }
        public bool isProvided { get; set; }
        public Nullable<int> orderID { get; set; }
        public Nullable<int> shipmentID { get; set; }
        public int supplierID { get; set; }
        public System.DateTime createdTime { get; set; }
        public string packageStatus { get; set; }
        public string notes { get; set; }
    
        public virtual Orders Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageContents> PackageContents { get; set; }
        public virtual Shipments Shipments { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Shipping Shipping { get; set; }
    }
}
