//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineWarehousingInformationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class receivedPackages
    {
        public int packageID { get; set; }
        public Nullable<int> shipmentID { get; set; }
        public System.DateTime createdTime { get; set; }
        public int supplierID { get; set; }
        public string supplierName { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string supplierAddress { get; set; }
        public string phoneNumber { get; set; }
        public string email { get; set; }
    }
}
