//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineWarehousingInformationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping
    {
        public int packageID { get; set; }
        public System.DateTime shippingDate { get; set; }
        public Nullable<System.DateTime> estimatedDeliveryDate { get; set; }
        public Nullable<System.DateTime> deliveryDate { get; set; }
        public string currentLocation { get; set; }
        public string currentStatus { get; set; }
        public string shippingNote { get; set; }
    
        public virtual Packages Packages { get; set; }
    }
}
